services:
  backend:
    image: backend:1.0.0
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      SERVER_PORT: 3000
      SERVER_HOST: 0.0.0.0
    networks:
      - app-network

networks:
  app-network:
    driver: bridge